CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text NOT NULL UNIQUE, role text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS guests (id text PRIMARY KEY, full_name text NOT NULL, phone text, email text, notes text, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS units (id text PRIMARY KEY, display_name text NOT NULL, slug text NOT NULL UNIQUE, property_label text, capacity_adults integer, capacity_children integer, active boolean DEFAULT true, default_check_in_time text, default_check_out_time text);
CREATE TABLE IF NOT EXISTS room_prices (id text PRIMARY KEY, unit_id text NOT NULL REFERENCES units(id), rate_code text NOT NULL DEFAULT 'standard', date text NOT NULL, amount_minor_units integer NOT NULL, currency text NOT NULL DEFAULT 'INR', created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE (unit_id, rate_code, date));
CREATE INDEX IF NOT EXISTS room_prices_date_unit_idx ON room_prices(date, unit_id);
CREATE TABLE IF NOT EXISTS room_availability (id text PRIMARY KEY, unit_id text NOT NULL REFERENCES units(id), date text NOT NULL, status text NOT NULL DEFAULT 'sold_off', reason text, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE (unit_id, date));
CREATE INDEX IF NOT EXISTS room_availability_date_unit_idx ON room_availability(date, unit_id);
CREATE TABLE IF NOT EXISTS reservations (id text PRIMARY KEY, reservation_number text NOT NULL UNIQUE, guest_id text NOT NULL REFERENCES guests(id), unit_id text NOT NULL REFERENCES units(id), check_in_date text NOT NULL, check_out_date text NOT NULL, booking_status text NOT NULL, payment_status text NOT NULL, adults integer NOT NULL, children integer NOT NULL, security_deposit_minor_units integer, payment_mode text, advance_received_minor_units integer, advance_received_at timestamptz, notes text, created_by text REFERENCES users(id), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS reservation_line_items (id text PRIMARY KEY, reservation_id text NOT NULL REFERENCES reservations(id), category text NOT NULL, description text NOT NULL, quantity integer NOT NULL, unit_label text, rate_minor_units integer NOT NULL, tax_rate real, amount_minor_units integer NOT NULL, sort_order integer NOT NULL);
CREATE TABLE IF NOT EXISTS invoices (id text PRIMARY KEY, invoice_number text NOT NULL UNIQUE, reservation_id text NOT NULL REFERENCES reservations(id), version integer NOT NULL, status text NOT NULL, issued_at timestamptz, currency text NOT NULL DEFAULT 'INR', subtotal_minor_units integer NOT NULL, tax_minor_units integer NOT NULL, security_deposit_minor_units integer NOT NULL, total_minor_units integer NOT NULL, advance_minor_units integer NOT NULL, balance_minor_units integer NOT NULL, amount_in_words text, snapshot_json text, created_by text REFERENCES users(id), created_at timestamptz NOT NULL, parent_invoice_id text, finalized_at timestamptz, finalized_by text REFERENCES users(id));
CREATE TABLE IF NOT EXISTS payment_attempts (id text PRIMARY KEY, invoice_id text NOT NULL REFERENCES invoices(id), invoice_version integer NOT NULL, provider text NOT NULL, provider_ref text, amount_minor_units integer NOT NULL CHECK (amount_minor_units > 0), currency text NOT NULL DEFAULT 'INR', status text NOT NULL DEFAULT 'created', upi_uri text, expires_at timestamptz NOT NULL, idempotency_key text NOT NULL UNIQUE, provider_payment_id text, paid_amount_minor_units integer, utr text, paid_at timestamptz, failure_code text, last_checked_at timestamptz, created_by text REFERENCES users(id), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS payment_events (id text PRIMARY KEY, provider text NOT NULL, provider_event_id text NOT NULL, event_type text NOT NULL, attempt_id text REFERENCES payment_attempts(id), signature_valid boolean NOT NULL, payload text NOT NULL, outcome text, error text, received_at timestamptz NOT NULL, processed_at timestamptz, UNIQUE (provider, provider_event_id));
CREATE TABLE IF NOT EXISTS invoice_payments (id text PRIMARY KEY, invoice_id text NOT NULL REFERENCES invoices(id), amount_minor_units integer NOT NULL, payment_mode text NOT NULL, payment_status text NOT NULL, received_at timestamptz, reference text, notes text, recorded_by text REFERENCES users(id), created_at timestamptz NOT NULL, attempt_id text REFERENCES payment_attempts(id), source text NOT NULL DEFAULT 'manual', provider_payment_id text);
CREATE TABLE IF NOT EXISTS qr_payment_artifacts (id text PRIMARY KEY, invoice_id text NOT NULL REFERENCES invoices(id), amount_minor_units integer NOT NULL, upi_id text NOT NULL, payee_name text NOT NULL, currency text NOT NULL DEFAULT 'INR', transaction_note text, upi_uri text NOT NULL, qr_format text NOT NULL, artifact_version integer NOT NULL, created_by text REFERENCES users(id), created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS share_links (id text PRIMARY KEY, invoice_id text NOT NULL REFERENCES invoices(id), token text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL, created_by text REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_events (id text PRIMARY KEY, actor_user_id text REFERENCES users(id), entity_type text NOT NULL, entity_id text NOT NULL, event_type text NOT NULL, before_json text, after_json text, request_id text, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS auth_challenges (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), otp_hash text NOT NULL, expires_at timestamptz NOT NULL, attempts integer NOT NULL DEFAULT 0, consumed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS payment_proofs (id text PRIMARY KEY, invoice_id text NOT NULL REFERENCES invoices(id), share_link_id text NOT NULL REFERENCES share_links(id), storage_provider text NOT NULL, storage_key text NOT NULL, mime_type text NOT NULL, size_bytes integer NOT NULL, status text NOT NULL, submitted_at timestamptz NOT NULL, reviewed_at timestamptz, reviewed_by text REFERENCES users(id), admin_note text, verified_amount_minor_units integer, payment_mode text, payment_reference text, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS push_subscriptions (id text PRIMARY KEY, endpoint text NOT NULL UNIQUE, p256dh text NOT NULL, auth text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);

CREATE UNIQUE INDEX IF NOT EXISTS payment_attempts_provider_ref_uq ON payment_attempts(provider, provider_ref) WHERE provider_ref IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS payment_attempts_provider_payment_uq ON payment_attempts(provider, provider_payment_id) WHERE provider_payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS payment_attempts_status_expiry_idx ON payment_attempts(status, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS payment_attempts_one_active_uq ON payment_attempts(invoice_id) WHERE status IN ('created', 'pending');
CREATE UNIQUE INDEX IF NOT EXISTS payment_proofs_one_pending_uq ON payment_proofs(invoice_id) WHERE status = 'pending_review';

CREATE UNIQUE INDEX IF NOT EXISTS invoice_payments_provider_payment_uq ON invoice_payments(provider_payment_id) WHERE provider_payment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS invoice_payments_upi_reference_uq ON invoice_payments(reference) WHERE payment_mode = 'UPI' AND reference IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS qr_artifacts_invoice_version_uq ON qr_payment_artifacts(invoice_id, artifact_version);
